
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: travel_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: travel_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: travel_bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/travel_bot
    volumes:
      - ./logs:/app/logs
      - ./templates:/app/templates:ro
    command: sh -c "sleep 5 && python -m bot.main"

volumes:
  postgres_data:
